reverse_proxy:
    image: ej52/alpine-nginx-proxy
    ports:
        - '80:80'
        - '443:443'
    restart: unless-stopped
    volumes:
        - '/var/run/docker.sock:/tmp/docker.sock:ro'

web:
    build: .
    ports:
        - '8000:80'
    restart: unless-stopped
    volumes:
        - .:/server/http
    links:
        - postgres
        - redis
    environment:
        VIRTUAL_HOST: samsara.docker

postgres:
    image: kiasaki/alpine-postgres
    ports:
        - '5432:5432'
    restart: unless-stopped
    volumes:
        - ./storage/app/database:/data
    environment:
        POSTGRES_USER: samsara
        POSTGRES_PASSWORD: arasmas
        POSTGRES_DB: samsara

redis:
    image: smebberson/alpine-redis
    ports:
        - '6379:6379'
    restart: unless-stopped
    volumes:
        - ./storage/app/redis:/data
